name: 'Setup Bun with Cache'
description: 'Sets up Bun runtime with dependency caching for faster CI'

inputs:
  bun-version:
    description: 'Bun version to install'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Cache Bun dependencies
      uses: actions/cache@v5
      with:
        path: ~/.bun/install/cache
        key: bun-${{ runner.os }}-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          bun-${{ runner.os }}-

    - name: Install dependencies
      run: bun install --frozen-lockfile
      shell: bash
